name: sleek_typography
description: Flexible way of customizing text.
version: 0.1.1
homepage: https://github.com/aloisdeniel/sleek_typography

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  freezed_annotation: ^0.7.1
  derived_colors: ^0.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner:
  freezed: ^0.10.4
  flutter_test:
    sdk: flutter

flutter:
